Revert "update to material components"
This reverts commit 4a02ba1a as we saw this issue

 kotlin.UninitializedPropertyAccessException: lateinit property folderView has not been initialized
        at eu.zderadicka.audioserve.fragments.FolderFragment.getFolderViewState(FolderFragment.kt:528)
        at eu.zderadicka.audioserve.fragments.FolderFragment.onSaveInstanceState(FolderFragment.kt:523)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)